### ISSUE TITLE
module 'razorpay' has no attribute 'Client'

### ISSUE THREAD

**Issue by mdb2301** [razorpay/razorpay-python#100]
I was trying to run a test integration of razorpay in python.

My code:
`**
import razorpay
client = razorpay.Client(auth=("******", "******"))

order_amount = 500
order_currency = 'INR'
order_receipt = 'order_rcptid_11'
notes = {'Shipping address': 'Bommanahalli, Bangalore'}   # OPTIONAL

print(client.order.create(amount=order_amount, currency=order_currency, receipt=order_receipt, notes=notes, payment_capture='0'))
**`

This generates error on run as:

**
Traceback (most recent call last):
  File "razorpay.py", line 1, in <module>
    import razorpay
    client = razorpay.Client(auth=("********", "R**********n"))
AttributeError: module 'razorpay' has no attribute 'Client'
**

My python version is 3.7.0

**Comment by shashikiranraifox** [comment]
I am facing the same issue. What is the fix applied ?
