### ISSUE TITLE
Unable to change the description in payments link page

### ISSUE THREAD

**Issue by pratsharma** [razorpay/razorpay-python#102]
Hello,

I am trying to create a payment link using the documentation here: https://github.com/razorpay/razorpay-python#payment-link
Here I am facing two issues:
1. The description I am setting is not getting reflected on payment page. Initially I can see the description I am setting but then it changes to invoice id after entire page is loaded.
2. I am trying to customize the payment link using the documentation here: https://razorpay.com/docs/payment-links/api/custom/
I need to know if I can modify the recipient's name in "Payment Request From" section in Payment Details section of the payment page ?

**Comment by ankitdas13** [comment]
@pratsharma Apologise for the long delay. i might be possible that the issue is from backend side. Could you please let us know is this issue was resolved or not?

**Comment by ankitdas13** [comment]
Closing this issue for now, due to not getting any response. Please don't let that stop you from re-opening if the issue is persisting for you. Let us know if you need any help.
