### ISSUE TITLE
No function/method to update a subscription

### ISSUE THREAD

**Issue by pupattan** [razorpay/razorpay-python#103]
Looks like there is no  function/method to update a subscription.

**Comment by sainipray** [comment]
Yes, In default library, it's not exist for update subscription. but you can using follow below code.

```
from razorpay import Subscription
    
def update_subscription(client, subscription_id, data):
        subs = Subscription(client=client)
        url = "{}/{}".format(subs.base_url, subscription_id)
        razor_subs = subs.patch_url(url, data)
        return razor_subs


```

**Comment by prashanthKumar69** [comment]
@sainipray how does the above code effect the payments if the subscription billing cycle is already started and if i am changing the plan in subscription?

**Comment by adhibhuta** [comment]
@pupattan @prashanthKumar69 How did you even create a plan, can't even create a plan

**Comment by hexdecimal16** [comment]
This seems so weird. In docs they have listed method for subscription but in library there aren't any methods.

**Comment by sanzzzay** [comment]
> @pupattan @prashanthKumar69 How did you even create a plan, can't even create a plan

Read this - https://github.com/razorpay/razorpay-python#plans
Underlying code -  https://github.com/razorpay/razorpay-python/blob/305f7311eb00f1541d16bbc4eb2a24c642e0e033/razorpay/resources/plan.py#L10

**Comment by pupattan** [comment]
Closing this issue as we got some solution. thanks
