### ISSUE TITLE
Incorrect parameters for refund on payment in doc and server error

### ISSUE THREAD

**Issue by mayurnewase** [razorpay/razorpay-python#105]
I am trying to create refund,doc here (https://razorpay.com/docs/api/refunds/) suggests to use
`resp = client.payment.refund(payment_id, payment_amount, notes=notes)`
I get unexpected argument "notes",as from code `def refund(self, payment_id, amount, data={}, **kwargs)` in resources/payment.py it accepts data dict.
Now after providing data dict as follow
`{
"speed" : speed, 
"notes" : notes, 
"receipt" : receipt
}`
I am getting "server error admins have been notified".

**Comment by ankitdas13** [comment]
@mayurnewase Could you please let us know if this issue has been resolved ? If it's resolved, then please close it.
Thanks @sanzzzay for helping here 👏
