### ISSUE TITLE
Add support for new payment links

### ISSUE THREAD

**Issue by dhaval-mehta** [razorpay/razorpay-python#108]
Existing payment link implementation will be deprecated. see: https://razorpay.com/docs/payment-links/api/v1/
New API link: https://razorpay.com/docs/payment-links/api/new/create/

**Comment by Vibhu-Agarwal** [comment]
@captn3m0 May I take up this issue?
- Won't replace the `Invoice` resource, will just add a [`DeprecationWarning`](https://docs.python.org/3/library/exceptions.html#DeprecationWarning) to its functions.
- Will add a new resource: `PaymentLinks` (resulting in `client` having an attribute of `paymentlinks`).

**Comment by Vibhu-Agarwal** [comment]
@harman28 ^^^

**Comment by gowthamvbhat** [comment]
Razorpay deprecated the old payment link api on Aug 15 2021 - [https://razorpay.com/docs/payment-links/api/v1/](url)

**Comment by ankitdas13** [comment]
@dhaval-mehta `Paymentlink` has already been implemented in one of recent releases , you can this [doc](https://github.com/razorpay/razorpay-python/blob/master/documents/paymentLink.md) for your reference

**Comment by ankitdas13** [comment]
Closing this issue for now . If you need any help then please let us know.
