### ISSUE TITLE
How to create a plan using the library

### ISSUE THREAD

**Issue by adhibhuta** [razorpay/razorpay-python#112]
When I am trying to create a plan by calling `client.plan.create(data=data)` its looking for an `item_id` where do I get the item id? 

If I create a plan using a curl request or postman as shown [here](https://razorpay.com/docs/api/subscriptions/#create-a-plan) it work perfectly fine and doesn't ask for an `item_id`, it creates one by itself and returns it back. 

But when I use `requests` to do the same post request like this-
`requests.post('https://api.razorpay.com/v1/plans', headers={"content-type":"application/json"}, data=data, auth=('key', 'secret'))`
 it gives the following error:
`{'error': {'code': 'BAD_REQUEST_ERROR', 'description': 'The interval field is required.', 'field': 'interval'}}`

I am using the same data as the postman request ie
```
{
  "period": "weekly",
  "interval": 1,
  "item": {
    "name": "Test plan - Weekly",
    "amount": 69900,
    "currency": "INR",
    "description": "Description for the test plan"
  },
  "notes": {
    "notes_key_1": "Tea, Earl Grey, Hot",
    "notes_key_2": "Tea, Earl Grey… decaf."
  }
}
```

**Comment by sanzzzay** [comment]
Basically, in this ```client.plan.create(data=data)``` you need to pass the `data` in the format which is given in request body the same which you have posted:
```
{
  "period": "weekly",
  "interval": 1,
  "item": {
    "name": "Test plan - Weekly",
    "amount": 69900,
    "currency": "INR",
    "description": "Description for the test plan"
  },
  "notes": {
    "notes_key_1": "Tea, Earl Grey, Hot",
    "notes_key_2": "Tea, Earl Grey… decaf."
  }
}

```
For example:
```
def create_plan(period, interval, item, notes=None):
        response = dict()
        if not period:
            return response
          data = {'period': period, 'interval': interval, 'item': item}  # these 3 params are mandatory - check [docs](https://razorpay.com/docs/api/subscriptions/#create-a-plan)
        if notes:
            data['notes'] = notes
        # get  Razorpay client  
        response_data = client.plan.create(data=data)
```
I hope this will work.

**Comment by ankitdas13** [comment]
This issue has been resolved. closing this issue for now . If you need any help then please let us know.
