### ISSUE TITLE
How to test the whole flow of Razorpay without a front end?

### ISSUE THREAD

**Issue by mrabhinv** [razorpay/razorpay-python#113]
For e.g.

I am using Django tests so if there was a way to get Razorpay signature without the need of a front end to provide it, it would make things easy.

**Comment by dhaval-mehta** [comment]
You can use mock from the unittest. 

Disclaimer: I am not from the Razorpay team.

**Comment by abhinavmarwaha** [comment]
What exactly do you mean by "mock" from the unit test?

**Comment by dhaval-mehta** [comment]
```python

    @mock.patch('razorpay.function')
    def test_payment(self, mock_razorpay_function):
        mock_razorpay_function.return_value = 'You can return anything. When your code calls this function, this value will be returned.'
        
```

**Comment by dhaval-mehta** [comment]
https://realpython.com/python-mock-library/

**Comment by ankitdas13** [comment]
@mrabhinv Could you please let us know if this issue has been resolved? If it's resolved, then please close this issue
Thanks @dhaval-mehta for helping 👏

**Comment by ankitdas13** [comment]
Closing this issue for now, due to not getting any response. If you need any help then please let us know.
