### ISSUE TITLE
Add support for Python 3.7 and 3.8

### ISSUE THREAD

**Issue by Vibhu-Agarwal** [razorpay/razorpay-python#114]
**Proposal**: Add support for Python3.7 and Python3.8
**Also requested**: in #76

**Rationale**
Python3.5 reached the EOL last month. So the library has support for 3.6 as the only Python version which is still maintained (but only for security patches). Python3.8 is the lowest version which is still accepting `bugfix` patches.

**Optional**
Drop support for Python3.3 as it's been over three years since its EOL (2017-09-29)

**Comment by ankitdas13** [comment]
@Vibhu-Agarwal Thank you for your proposal & I apologize for the long delay. Support for Python `v3.7` to `v3.10` has already been added in latest releases.

**Comment by ankitdas13** [comment]
Closing this issue for now. If you need any help then please let us know.
