### ISSUE TITLE
Notes should be provided as a dictionary

### ISSUE THREAD

**Issue by Aekanshu** [razorpay/razorpay-python#119]
hi I have cre4ated a simple program and when I tried to create an order then I got this error :- 

**razorpay.errors.BadRequestError: Notes should be provided as a dictionary**

My code is :-

```
name = "name"
order_amount = 100000
order_currency = 'INR'
order_receipt = str(1)

created_notes = {"this payment is done by" : "an_email", "this payment is done for" : "another email"}

create_order = razorpay_client.order.create(dict(amount=order_amount, currency=order_currency, receipt=order_receipt, notes=created_notes))
            
```

without notes it is working fine 

what should i do ?

**Comment by Aekanshu** [comment]
Hey guys the problem has been resolved as the problem was that i was using an older version of razorpay i.e. 0.1 but now version 1.2.0 is available so as soon as I upgraded my  library with `pip install razorpay --upgrade` all problems has been resolved .

**Comment by Kumarsatwik** [comment]
Thanks .It help me
