### ISSUE TITLE
Need product detail in Webhook payment response.

### ISSUE THREAD

**Issue by youngking1686** [razorpay/razorpay-python#123]
I am trying to use the webhook response of any payments to do my backend updation on my client's purchases. But I don't see for which product/payment page the client has paid for, right now I have only subscription plans and classifying them based on the amount that has been paid, I know it sounds stupid. Please someone clarify if I am missing any detail here or any help is much appreciated. All I want is a response message with the product, amount and customer details so that i can update my end and offer the service. I am using python on flask framework.

**Comment by devansh-chotai** [comment]
you can try passing the product and customer info in the notes section and retrieve it in the webhook

**Comment by ankitdas13** [comment]
@youngking1686 Could you please let us know if this issue has been resolved ?

**Comment by ankitdas13** [comment]
Closing this issue for now, due to not getting any response. If you need any help then please let us know.
