### ISSUE TITLE
Support for multiple currencies?

### ISSUE THREAD

**Issue by vivekhub** [razorpay/razorpay-python#129]
I am trying to create an order using USD as currency.  I am calling order.create() with currency as 'USD' and I get a BadRequestError with Currency not supported message.  What am I doing wrong  ?

**Comment by Anil-matcha** [comment]
Facing the same issue, any help here ?

**Comment by Anil-matcha** [comment]
Thanks for sharing it. It seems the account has to be setup for accepting international payments. There is a procedure for it mentioned here https://razorpay.com/docs/payment-gateway/payments/international-payments/#enable-international-payments

**Comment by vivekhub** [comment]
Thanks for the update.  I am going to close this issue for now.
