### ISSUE TITLE
Payments are not auto captured

### ISSUE THREAD

**Issue by osmarghyadeep** [razorpay/razorpay-python#131]
So suppose we created an order -> order_a (state: created)
Also we did the payment -> payment_a (state: authorized)

Auto capturing of payments is turned on.

Issue 1: Payments are not auto captured - not sure why
As of now - we have a work around - we are explicitly calling the api to capture the payment

But still this is an issue as --
- Is the feature meant to be deprecated, or 
- There is really an issue

I was working in test environment

**Comment by ankitdas13** [comment]
Duplicate of #132

**Comment by ankitdas13** [comment]
Closing this issue because this issue is duplicate of #132 and we don't got any response also the issue is not related to the sdk.
