### ISSUE TITLE
client.order.create(amount=order_amount, currency=order_currency, receipt=order_receipt, notes=notes) gives error!

### ISSUE THREAD

**Issue by epsi95** [razorpay/razorpay-python#133]
In the documentation mentioned  [here](https://razorpay.com/docs/payment-gateway/web-integration/standard/#step-1-create-an-order-from-your-server), the way to create `order_id` is
```python
order_amount = 50000
order_currency = 'INR'
order_receipt = 'order_rcptid_11'
notes = {'Shipping address': 'Bommanahalli, Bangalore'}   # OPTIONAL
client.order.create(amount=order_amount, currency=order_currency, receipt=order_receipt, notes=notes)
````

But upfortunately it does not work giving an error
```
.
.
.
 File "/home/probhakar/Python_VENVs/ai/lib/python3.8/site-packages/razorpay/client.py", line 119, in request
    response = getattr(self.session, method)(url, auth=self.auth,
  File "/home/probhakar/Python_VENVs/ai/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
TypeError: request() got an unexpected keyword argument 'amount'
```

The way to handle this
```python
            order_id = razorpay_client.order.create({
                    "amount": 50000,
                    "currency": "INR",
                   "receipt": 'order_rcptid_11'
            })
```

It seems Razorpay using requests and REST apis under the hood and they are directly passing the arguments to `requests` method.

Kindly update the documentation accordingly.

**Comment by FIRDOUS-BHAT** [comment]
@epsi95 Got the same error on using there documentation. Razorpay still has not updated the documentation.

**Comment by ankitdas13** [comment]
@epsi95 Thank you for raising this issue. The documentation has already been updated. please feel free to re-open it or you can report on the support [portal](https://razorpay.com/support/)

**Comment by ankitdas13** [comment]
The issue has been fixed. Closing this issue for now. If you need any help then please let us know.
