### ISSUE TITLE
Unable to fetch more than 10 payments of a virtual account

### ISSUE THREAD

**Issue by mahefooz** [razorpay/razorpay-python#138]
As per documentation, it says we can fetch 10 to 100 payments made to a virtual account, but in Python SDK, we don't have option to use 'count' variable to fetch more than 10 payments.

`client.virtual_account.payments(virtual_account_id=va_id)`

In the above function, it is taking only virtual account id, how to resolve this issue?

**Comment by ankitdas13** [comment]
@mahefooz Apologise for the long delay. Could you please let me know is it resolved or not? 
For your reference, you can check this [doc](https://razorpay.com/docs/api/payments/smart-collect/#fetch-payments-for-a-virtual-account) or use this code sample

`options = {"count": 10}`
`client.virtual_account.payments(virtualId,options)`

**Comment by ankitdas13** [comment]
Closing this issue due to not getting any response. Please update to the most recent version to resolve this issue and try the code snippet which I shared to you. If you need any help then please let us know.
