### ISSUE TITLE
'Client' object has no attribute 'payment_link'

### ISSUE THREAD

**Issue by sid-khullar** [razorpay/razorpay-python#152]
The following code results in the error below. Unsure how to proceed. Thanks!
```AttributeError: 'Client' object has no attribute 'payment_link'```

I'm using Python 3.9.1 and while I'm aware this version of python isn't supported, will it cause the stated error?

```
import razorpay

# test mode
key_id = "snipped"
key_secret = "snipped"

client = razorpay.Client(auth=(key_id, key_secret))
order_data = {
    "amount": 5000,
    "currency": "INR",
    "receipt": "RECEIPT",
    "notes": "a description"
}

payment_link_id = client.payment_link.create(data=order_data)
```

**Comment by moonlightCoder2002** [comment]
@sid-khullar 
I guess the version here is not the problem. I got the same error and looks like razorpay team has not updated payment_ link method. If you want you can use old method of generating payment link using invoice methods. Refer https://razorpay.com/docs/payment-links/api/v1/create/
