### ISSUE TITLE
Unable to create subcriptions 

### ISSUE THREAD

**Issue by Amaranath1994** [razorpay/razorpay-python#155]
I am trying to create a subscription using APIs. 

Here is my code 

`import requests
data = {
  "plan_id":"plan_IN0gNyprphoxy0",
  "total_count":12,
  "quantity":1,
  "start_at":1637221418,
  "expire_by":1699620766,
  "customer_notify":1,
  
"notify_info":{
    "notify_phone":"8888888888",
    "notify_email":"abc@gmail.com"
  }

}
response = requests.post('https://api.razorpay.com/v1/subscriptions', headers={"content-type":"application/json"}, 
                         data=data, auth=(KEY, VALUE))
print(response)
print (response.json())`

But I am getting following error - 

Response [400]>
{'error': {'code': 'BAD_REQUEST_ERROR', 'description': 'The plan id field is required.', 'field': 'plan_id'}}

Can someone help me with this ?

Note - plan_IN0gNyprphoxy0 is valid plan id.

**Comment by Amaranath1994** [comment]
Here is the snippet of the code - 
![image](https://user-images.githubusercontent.com/51707429/142584103-5cae04ab-386b-4f7c-a219-3b6b88e84f8b.png)

**Comment by sanzzzay** [comment]
```
        data = {'plan_id': plan_id, 'total_count': total_count, 'quantity': quantity}
        if notes:
            data['notes'] = notes
        client = # get_razorpay_client
        response_data = client.subscription.create(data=data)
```
This will do.

**Comment by ankitdas13** [comment]
@Amaranath1994 Apologise for the long delay. Could you please let us know if this issue has been resolved ? It would have worked if you added their  `json.dump` at data, and also using our SDK would have make it much easier for you .

<img width="983" alt="Screenshot 2022-11-22 at 6 02 11 PM" src="https://user-images.githubusercontent.com/89454448/203315743-eb2db077-ecf6-4f38-8ab4-b3e3ba9e63cb.png">

**Comment by ankitdas13** [comment]
Closing this issue for now, due to not getting any response, I have also tried this issue from my end and it's working . If you are still facing this same issue, please update to the most recent version to resolve this issue. If you need any help then please let us know.
