### ISSUE TITLE
razorpay.errors.BadRequestError: Amount exceeds maximum amount allowed.

### ISSUE THREAD

**Issue by aman162000** [razorpay/razorpay-python#156]
I am trying to create an order but this error occurred. I also tried to create order using API but it also throw the same error.

```
{
    "error": {
        "code": "BAD_REQUEST_ERROR",
        "description": "Amount exceeds maximum amount allowed.",
        "source": "business",
        "step": "payment_initiation",
        "reason": "input_validation_failed",
        "metadata": {},
        "field": "amount"
    }
}
```

**Comment by ankitdas13** [comment]
@aman162000 Apologise for the long delay . Could you please let us know is this issue was resolved? Your amount might be greater than 9 lakh, which might cause this error.

**Comment by aman162000** [comment]
I just changed the API keys and it worked.

**Comment by ankitdas13** [comment]
Thanks @aman162000  for confirming us. We are closing this issue for now, but if you still have any questions, please feel free to ask or you can connect to the support [portal](https://razorpay.com/support/).
