### ISSUE TITLE
No response from the verify_payment_signature function

### ISSUE THREAD

**Issue by rjbanna** [razorpay/razorpay-python#162]
Hello all,

There is one function to verify the payment signature i.e. verify_payment_signature, but when I called that function, it returned nothing even if the signature was correct. So I took a look at the source code, and found that there is no return statement in that function, and that was the reason, I was getting None as the response. So I kindly request the Razorpay developers to add the return statement in the verify_payment_signature function. I changed the source code from my side and I found it to be working.

Path to file: razorpay/utility/utility.py

**Comment by pratyush3124** [comment]
Hey all,
I have the same problem.
The code here is updated but not in pip.
Please update it so that we can use the files for 'pip install razorpay'.

**Comment by ankitdas13** [comment]
@rjbanna My apologies for the long delay and also for the difficulties you have encountered. Could you let us know if this issue was resolved ? The changes are already updated in Pip

**Comment by ankitdas13** [comment]
Closing this issue for now, due to not getting any response. If you are still facing this same issue, please update to the most recent version to resolve this issue. Please let us know if you need any help.
