### ISSUE TITLE
Razorpay Verify Payment Signature Failed with Valid Signature

### ISSUE THREAD

**Issue by varun-jaggi** [razorpay/razorpay-python#178]
Hi,

i am trying to use Verify Signature payment func to verify my payments exactly like this
 `client.utility.verify_payment_signature(params_dict)`
but it fails with 'Razorpay Verify Payment Signature Failed'

The github razorpay code contains Verify Signature functions but it is not updated on Pip.

also i need clarity on verify_payment_signature and verify_subscription
as my model works in subscription mode.

To Note:
- Using Django' serializer to validate the payload(which contains order_id, subscription_id, signature) in my own API

@kumarishan @Hashfyre @captn3m0 @gaurav1068

**Comment by jashandeep1659** [comment]
did you find solution

**Comment by ankitdas13** [comment]
@varun-jaggi My apologies for the long delay and also for the difficulties you have encountered. Could you let us know if this issue was resolved ? The changes are already updated in Pip

**Comment by ankitdas13** [comment]
Closing this issue for now, due to not getting any response. If you are still facing this same issue, please update to the most recent version to resolve this issue. Please let us know if you need any help.

**Comment by Yaswanth820** [comment]
I am still facing this issue with `client.utility.verify_payment_signature(params_dict)`. It fails every time with this exception `Razorpay Verify Payment Signature Failed` even when the details provided are correct.

For a quick work around I am manually generating a `hmac_signature` and comparing it with `razorpay_signature` as per the [documentation](https://razorpay.com/docs/api/payments/subscriptions/#payment-verification).
