### ISSUE TITLE
Razorpay Payment Link

### ISSUE THREAD

**Issue by moonlightCoder2002** [razorpay/razorpay-python#184]
Hi, I am trying to make razorpay payment link using API  in django but cannot do so because client cannot recognise the payment_link function. I am getting the below error while creating the payment link:-

**'Client' object has no attribute 'payment_link'** 

Kindly look into the matter.

**Comment by rohitsangwan01** [comment]
@moonlightCoder2002 try this

client.invoice.create(data={
        "customer": {
            "name": "Test",
            "email": "test@gmail.com",
            "contact": "12345"
        },
        "type": "link",
        "view_less": 1,
        "amount": 100,
        "currency": "INR",
        "description": "Payment link for Testing",
    })

this function will sned payment link to email + contact

**Comment by moonlightCoder2002** [comment]
@rohitsangwan01 
I have already implemented this method but I was wondering why isn't the method specific to payment link working. I wanted to use payment_link method because it is specific to my work. I guess razorpay team hasn't yet updated it. Anyways, thanks for your help.

**Comment by sid10on10** [comment]
@rohitsangwan01 It has been implemented in the SDK you can create a payment link using client.payment_link.create

**Comment by ankitdas13** [comment]
Closing this issue because it has already been implemented in one of recent releases
