### ISSUE TITLE
python kivy integration

### ISSUE THREAD

**Issue by sunilk-n** [razorpay/razorpay-python#185]
Is there any example for integrating the razorpay api inside the kivy module which will help to make payments for android applications using kivy

**Comment by kkyusufk** [comment]
Hey @sunilk-n as far as I can tell, this library should work fine in Kivy since it has support for python modules. So no extra step should be required.
Please let us know if you faced any challenges while using this module in Kivy and we can surely look into it.

**Comment by ankitdas13** [comment]
Closing this issue for now due to not getting any response. Please let us know if you need any help.
