### ISSUE TITLE
How to use options in payment.all() ?

### ISSUE THREAD

**Issue by akroushan** [razorpay/razorpay-python#22]
options : from, to, count and skip : How it can be used in python library ?

**Comment by gaurav1068** [comment]
Hi @akroushan,
For using from, to, count, skip pass these as extra params in dict 
e.g
for fetching all payments default call would be 
client = razorpay.Client(auth=("<key>", "<secret>"))
client.payment.fetch_all()

for fetching with extra params it will be :
client.payment.fetch_all({'count':20})

similarly you can use other params also.
