### ISSUE TITLE
How to automate the modal payment flow via API

### ISSUE THREAD

**Issue by bhasinrajesh** [razorpay/razorpay-python#228]
I am trying to automate the payment part of razorpay in my test to check ordering on our website.The problem is for the  final step of payment I am not able to automate it using just APIs - since it uses the payment modal of razorpay and i have not been able to find the corresponding APIs for it.

I tried with createPaymentJson

payment = client.payment.createPaymentJson({
  "amount": "2500",
  "currency": "INR",
  "email": "gaurav.kumar@example.com",
  "contact": "9123456789",
  "order_id": "order_KFusTJQtqZ4vVg",
  "method": "netbanking",
  "bank": "HDFC"
})

but even that is showing  - `razorpay.errors.BadRequestError: The requested URL was not found on the server.`

**Comment by bhasinrajesh** [comment]
Yeah we did make a query using our business account.It didnt quite work like we expected.Thanks anyways you can close this.

**Comment by ankitdas13** [comment]
Thanks @bhasinrajesh for confirming us. We are closing this issue for now, but if you still have any questions, please feel free to ask or you can connect to the support [portal](https://razorpay.com/support/).
