### ISSUE TITLE
Setting up webhook

### ISSUE THREAD

**Issue by Vaibhavs10** [razorpay/razorpay-python#23]
Hey!

I am new to razorpay and have to setup a payment gateway for one of my products,
We have our application stack built on Flask (microframework in python)

I am unable to figure out the steps to build a payment gateway and how to setup a webhook

Can you please help me out with this?

**Comment by gaurav1068** [comment]
@Vaibhavs10 Please refer to this https://github.com/razorpay/razorpay-python-testapp

**Comment by Vaibhavs10** [comment]
@gaurav1068 Thank you for sharing this link with me, I was wondering how can I integrate a form with this, right now all the data is transferred using Javascript, TIA :)

**Comment by gaurav1068** [comment]
closing as no further action is required
