### ISSUE TITLE
Support for python 3.10

### ISSUE THREAD

**Issue by guptavartika** [razorpay/razorpay-python#240]
The documentation says python 3.6 is the latest version supported so far. Since it is pretty old version now, can someone confirm if the latest version is compatible and safe to use with python 3.10 ?

**Comment by ankitdas13** [comment]
@guptavartika Sorry for the delay .The SDK works fine for me with Python 3.10.5. If you are getting any issue with v3.10 then please let us know we can help you

**Comment by ankitdas13** [comment]
Closing this issue for now, due to not getting any response. If you are facing any issue with v3.10 then please let us know so we can help you
