### ISSUE TITLE
hmac.compare_digest does not exist in Python < 2.7.7 

### ISSUE THREAD

**Issue by chetandhembre** [razorpay/razorpay-python#26]
I am getting  `AttributeError: 'module' object has no attribute 'compare_digest'`. I am using Python 2.7.6.
why not fall back to simple string compare if python version is less than 2.7.7.
I can make pull request if you want to.

**Comment by chetandhembre** [comment]
related https://github.com/razorpay/razorpay-python/pull/27

**Comment by captn3m0** [comment]
The reason is to prevent timing attacks:

>When comparing the output of digest() to an externally-supplied digest during a verification routine, it is recommended to use the compare_digest() function instead of the == operator to reduce the vulnerability to timing attacks.

We'll need to implement a constant-timing comparison to prevent that. If you can edit your PR to accommodate that, we'll be happy to merge and do a new release.

**Comment by captn3m0** [comment]
Python 2.7.6 was released on November 10, 2013, more than 3.5 years back. `2.7.6` is no longer supported as per my understanding. We're still looking to push a fix for this, but you are already behind on the security fixes, and I'd recommend upgrading.

**Comment by captn3m0** [comment]
In progress: https://github.com/razorpay/razorpay-python/pull/29/files

**Comment by vijayreddy1991** [comment]
when i am try to install python2.7.6 officially supported for ubuntu14.04 getting this error CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.DeprecatedIn23,
