### ISSUE TITLE
Auto Capturing Payment  flow is not working

### ISSUE THREAD

**Issue by pkatloktra** [razorpay/razorpay-python#3]
In order to send order_id in checkout form for auto capture payment 
I am creating order by: client.order.create(data=DATA)

Where DATA = {'amount': 200, 'currency': 'INR', 'receipt': 200, 'payment_capture': "true"}
I also  tried DATA = {'amount': 200, 'currency': 'INR', 'receipt': 200, 'payment_capture': True}

It is showing error BadRequestError: validation.boolean

Please help me with the issue.

**Comment by gaurav1068** [comment]
You need to pass DATA = {'amount': 200, 'currency': 'INR', 'receipt': 200, 'payment_capture': 1}

closing the issue
