### ISSUE TITLE
Handling Connection Error

### ISSUE THREAD

**Issue by anuragsingh722** [razorpay/razorpay-python#31]
How do we catch connection error **'Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')**, which usually comes after submitting the payment request from frontend via **Automatic Checkout**. 

As I understand, there is no call made to action url in above case, so I can't catch the error in our backend. Hence it ends up in a 500 error usually.
We would want to redirect him to payment page again, with an error "Payment failed, please try again".

**Comment by AditSoni** [comment]
got any updates regarding this ?
