### ISSUE TITLE
Redirecting from payment using link

### ISSUE THREAD

**Issue by SaptakS** [razorpay/razorpay-python#32]
Right now, when I make a payment using the payment url and the payment is success I am taken to the below page.
![screen shot 2017-09-04 at 4 39 33 pm](https://user-images.githubusercontent.com/9530293/30024051-aaaf2d78-918f-11e7-9905-7e82aed01daf.png)

I want to redirect to my website. Any help is appreciated

**Comment by jitendra-1217** [comment]
Hi @SaptakS , this feature is available with us now. For early access please drop us an email at integrations@razorpay.com and we'll take it up from there.

**Comment by SaptakS** [comment]
@jitendra-1217 thanks
