### ISSUE TITLE
razorpay.errors.BadRequestError: 0 is/are not required and should not be sent

### ISSUE THREAD

**Issue by shivambats** [razorpay/razorpay-python#44]
While creating the invoice, I am getting Bad Request Error

Below is how I am requesting the API,

DATA = '{"type":"invoice", "customer":{ "name": "Name", "email":"email", "contact":"919899XXXXXX", "billing_address":{ "line1":"318 C-Wing, Suyog Co. Housing Society Ltd., T.P.S Road, Vazira, Borivali", "city":"West Mumbai", "state":"Maharashtra", "zipcode":"400092", "country":"India" } }, "line_items":[ { "name":"Book / English August", "description":"Funny story of an IAS officer wanting to be aything other than an IAS.", "amount":200, "currency":"INR", "quantity":1 }, { "item_id": "item_gHQwerty123ggd" } ], "currency":"INR", "sms_notify": "1", "email_notify": "1"}'

client.invoice.create(data=DATA)

Thanks,

**Comment by Kalpa916** [comment]
remove recipt
