### ISSUE TITLE
pip installation failure May 3 2018, Re-opening Issue #1

### ISSUE THREAD

**Issue by msj2** [razorpay/razorpay-python#46]
Hi,
I'm on Ubuntu 16.04
python 2.7.12
pip 9.0.1
(& yes, my internet connection is very much working, .. files.pythonhosted.org is down but from quite some time... )
I tried
sudo pip install razorpay

It throws Error. Tries 4 times & then gives up.

Pasting the pip error log below.

Collecting razorpay Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2243c15c50>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /packages/a6/15/20ec9a2bdc11496a689c660c696399e1a5488c47fbfde2f8e9cb1a958ae1/razorpay-1.1.1.tar.gz Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2243c15710>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /packages/a6/15/20ec9a2bdc11496a689c660c696399e1a5488c47fbfde2f8e9cb1a958ae1/razorpay-1.1.1.tar.gz Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2243c15490>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /packages/a6/15/20ec9a2bdc11496a689c660c696399e1a5488c47fbfde2f8e9cb1a958ae1/razorpay-1.1.1.tar.gz Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2243c20b50>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /packages/a6/15/20ec9a2bdc11496a689c660c696399e1a5488c47fbfde2f8e9cb1a958ae1/razorpay-1.1.1.tar.gz Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2243c20e50>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /packages/a6/15/20ec9a2bdc11496a689c660c696399e1a5488c47fbfde2f8e9cb1a958ae1/razorpay-1.1.1.tar.gz Exception: Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main status = self.run(options, args) File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 324, in run requirement_set.prepare_files(finder) File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files ignore_dependencies=self.ignore_dependencies)) File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file session=self.session, hashes=hashes) File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 821, in unpack_url hashes=hashes File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 659, in unpack_http_url hashes) File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 853, in _download_http_url stream=True, File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/sessions.py", line 488, in get return self.request('GET', url, **kwargs) File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 386, in request return super(PipSession, self).request(method, url, *args, **kwargs) File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/sessions.py", line 475, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/sessions.py", line 596, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send resp = super(CacheControlAdapter, self).send(request, **kw) File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/adapters.py", line 487, in send raise ConnectionError(e, request=request) ConnectionError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/a6/15/20ec9a2bdc11496a689c660c696399e1a5488c47fbfde2f8e9cb1a958ae1/razorpay-1.1.1.tar.gz (Caused by NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2243c20890>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

Looking fwd to resolution.

Any backup/mirror link is appreciated.

Thanks, 
-MSJ.

**Comment by Krishnaraj-K** [comment]
HI Mallikarjuna, 

On Ubuntu 18.04, I am also facing the same issue what exactly you are facing, did you find the fix for the same, if yes, Requesting you to please share the steps, so that i can also fix in my environment. 

Thanks and Regards,
Krishnaraj

**Comment by harman28** [comment]
I apologise for the lack of response here. Leaving a reply anyway in case someone else comes looking.

> Network is unreachable

I believe this implies a connectivity issue. If you or anyone else is facing this, test whether other packages are getting installed correctly. Closing for now as it seems unrelated to the package.
