### ISSUE TITLE
Integrating Razorpay with Saleor e-commerce app

### ISSUE THREAD

**Issue by kuntalk** [razorpay/razorpay-python#48]
I am trying to integrate razorpay with Saleor, django based e-commerce app. There is no help in internet.
Saleor is using django-payment module for payment processing. There are only few payment gateways that supports django-payment and all of them are based out of India. Can I get some guidance or help so that I can integrate with Saleor?

[Link to Saleor github](https://github.com/mirumee/saleor)
[Link to django-payment](https://github.com/mirumee/django-payments)

Thank you

**Comment by oxalorg** [comment]
To be honest, it would be better if this discussion is taken over to django-payments repo instead of the Razorpay sdk repo.

Here's an issue discussing the exact same thing: https://github.com/mirumee/django-payments/issues/189
