### ISSUE TITLE
Getting payment details, history of a particular customer.

### ISSUE THREAD

**Issue by karankapoor229** [razorpay/razorpay-python#49]
Is there a way to get Billing details of a particular customer? I looked at the Razorpay Dashboard as well as the API Docs but found nothing.

**Comment by captn3m0** [comment]
This repo is only for issues specific to our Python SDK. Please send support requests to support@razorpay.com.

A [customer entity](https://razorpay.com/docs/getting-started/customers/#fetching-a-customer-using-id) is limited, but you might wanna look at [Invoices](https://razorpay.com/docs/invoices/operations/#issuing-an-invoice) instead
