### ISSUE TITLE
'Client' object has no attribute 'set_app_details'

### ISSUE THREAD

**Issue by krngd2** [razorpay/razorpay-python#51]
I am getting this error while adding payment method to my Flask app
'Client' object has no attribute 'set_app_details'
razorpay_client = razorpay.Client(auth=(xxxxxxx", "xxxxxx"))
razorpay_client.set_app_details({"title" : "ML Captcha Prediction", "version" : "0.5"})

**Comment by kaliaabhishek** [comment]
Hi @krngd2 ,
This might be an issue with the virtual environment if you are using one. Can you share the repository link that I can look into?

**Comment by f3n1Xx** [comment]
@krngd2 still getting this error?

**Comment by sanjaykhanssk** [comment]
Have you **figure out how to solve**  , because **i too getting same error**

**Comment by sanjaykhanssk** [comment]
just downloaded the [zip from this repo](https://github.com/razorpay/razorpay-python/releases/tag/1.2.0), after that : 
`python setup.py install`
it works..
Close this issue.
