### ISSUE TITLE
creating payment link

### ISSUE THREAD

**Issue by anupamme** [razorpay/razorpay-python#53]
Hello

I am looking to create a payment link programmatically e.g.

https://dashboard.razorpay.com/#/app/paymentlinks/new

Can you tell me how it can be done?

**Comment by kaliaabhishek** [comment]
Looking at the API documentation along with several client libraries, it seems that creating payment links programmatically is not possible. I think the dev team can look into this with more detail.

**Comment by radhika-tk** [comment]
@anupamme , @kaliaabhishek : It is possible to create payment links programatically too. Refer the product documentation on the website: https://razorpay.com/docs/payment-links/api/

**Comment by kaliaabhishek** [comment]
@radhika-tk thanks!

**Comment by varunajmera0** [comment]
client.invoice.create(data={
              "customer": {
                "name": "Varun Test",
                "email": "varuna@gmail.com",
                "contact": "1234567"
              },
              "type": "link",
              "view_less": 1,
              "amount": 2000,
              "currency": "INR",
              "description": "Payment link for this purpose - xyz.",
            })

**Comment by anupamme** [comment]
So once a user makes a payment how will we get the status of this payment (programatically)?

Because we dont have a payment id here which we can query your API(s).

**Comment by harman28** [comment]
Sorry for the delay, adding a response here anyway for anyone else who might come looking.

You'll need to subscribe to [webhooks](https://razorpay.com/docs/webhooks/) to be notified of payments. This will give you the ID to query too. For specific invoices, you can also query directly using the invoice ID, checking status.
