### ISSUE TITLE
Most excepts are of razorpay.errors.BadRequestError. This should be returning specific exceptions and error codes.

### ISSUE THREAD

**Issue by mevinbabuc** [razorpay/razorpay-python#55]
Most of the exceptions are `razorpay.errors.BadRequestError`, this should be little more specific by returning proper exceptions or error codes, so its easy to handle these errors when implementing.

Probably have a base class of Exceptions as mentioned here #52 and have sub classes for each errors like customer already exists etc, rather than returning `razorpay.errors.BadRequestError`

**Comment by harman28** [comment]
There is a an ongoing effort to start returning specific error codes, which our library will be able to consume. Till then, exception will need to be handled in a common place, or using error descriptions (which are specific).
