### ISSUE TITLE
Feature Request: Get all Authorized payments

### ISSUE THREAD

**Issue by OmPrakash95** [razorpay/razorpay-python#57]
I'm looking for a method through which I can fetch all Authorized payments and list it just like how it is in the razorpay dashboard where I can filter the list of payments with the help of its statuses such as 'Authorized' ' Captured' 'Refund' etc.

**Comment by harman28** [comment]
Currently this functionality is only available on dashboard, and not via API. For this reason, the python package won't be able to implement it either. You can fetch orders with authorized payments though, if that is your real requirement: [Link](https://razorpay.com/docs/api/orders/#query-parameters)
