### ISSUE TITLE
Retrieve payments for given time range.

### ISSUE THREAD

**Issue by dhaval-mehta** [razorpay/razorpay-python#59]
I have a case where I want to retrieve payments for given time range. For example, I want to retrieve payments done between 9 PM to 10 PM on 21st January 2019. I have checked docs of razorpay and I found that I need to pass two query parameters "from" and "to". You can read docs from: [https://docs.razorpay.com/docs/payments](https://docs.razorpay.com/docs/payments)

I did not find anything in python sdk. Can anyone help me?

**Comment by varunajmera0** [comment]
Here is def: You can pass in data. I think.
https://github.com/razorpay/razorpay-python/blob/master/razorpay/resources/payment.py

def all(self, data={}, **kwargs):
        """"
        Fetch all Payment entities
        Returns:
            Dictionary of Payment data
        """
        return super(Payment, self).all(data, **kwargs)

**Comment by harman28** [comment]
@dhaval-mehta As noted about, the data dictionary allows you to pass all accepted parameters, including from and to.
