### ISSUE TITLE
Razorpay signature verification failure

### ISSUE THREAD

**Issue by SurajB** [razorpay/razorpay-python#65]
I am trying to integrate razor pay payment link through python SDK. While trying to verify the signature sent in header with the web hook response from razor pay, I get the following error. 

`
File "/var/task/services/loan_repayment_service.py", line 569, in initiate_update_repayment
  client.utility.verify_webhook_signature(body_string, signature, api_key)
  File "/var/task/razorpay/utility/utility.py", line 25, in verify_webhook_signature
  self.verify_signature(body, signature, secret)
  File "/var/task/razorpay/utility/utility.py", line 45, in verify_signature
  'Razorpay Signature Verification Failed')
`

I have used the same code provided in the Razor Pay API documentation to validate the signature - https://razorpay.com/docs/webhooks/integrations/#validation

Converted the response body to string using json.loads() and passed to razor pay signature verification function along with signature and secret key configured in razor pay.

`
client = razorpay.Client(auth=(key, secret))
client.utility.verify_webhook_signature(body_string, signature, api_key)
`

Also ran a standalone script to generate a signature by passing secret key and web hook response body using hmac. But the signature produced doesn't match with the signature sent in web hook header.

`
key = bytes(key, 'utf-8')
body = bytes(body, 'utf-8')
`

`dig = hmac.new(key=key, msg=body, digestmod=hashlib.sha256)`
`generated_signature = dig.hexdigest()`

**generated_signature** doesn't match with the web hook header signature.

I have tried the solution posted in this question but it doesn't seem to work - https://stackoverflow.com/questions/53706973/razorpay-webhook-signature-verification-error

So how to resolve the signature verification issue? What could be the problem?

**Comment by captn3m0** [comment]
>Converted the response body to string using json.loads() and passed to razor pay signature verification function along with signature and secret key configured in razor pay.

This is incorrect. Please don't parse the request body, and instead use the raw response body.

See https://docs.djangoproject.com/en/2.2/ref/request-response/#django.http.HttpRequest.body on how to read it in Django.

**Comment by SurajB** [comment]
Thanks for the response. 

"Converted the response body to string using **json.loads()** and passed to razor pay signature verification function along with signature and secret key configured in razor pay."

Sorry that was my bad. I meant json.dumps(). Was trying to convert the raw json response to string and then pass it to verify the signature. That gave us the error as mentioned in earlier comment -  'Razorpay Signature Verification Failed'.

However when we tried passing the raw response body to verify the signature, we get the following error - 
`File "/var/task/services/loan_repayment_service.py", line 568, in initiate_update_repayment
  client.utility.verify_webhook_signature(body, signature, api_key)
  File "/var/task/razorpay/utility/utility.py", line 25, in verify_webhook_signature
  self.verify_signature(body, signature, secret)
  File "/var/task/razorpay/utility/utility.py", line 30, in verify_signature
  body = bytes(body, 'utf-8')
TypeError: encoding without a string argument`

The code in razorpay library is trying to convert the string to bytes and it fails when we pass raw response body.

Let me know if I am missing something here

**Comment by jitendra-1217** [comment]
The util method i.e. verify_signature expects string body. In general most frameworks have method to get request body as string (e.g. python's flask, php's laravel/symfony etc).  But with django I see it has one way (i.e. HttpRequest.body) which returns body as bytestring instead of string.

Suggest you to decode bytestring to string then pass it to the Razorpay's sdk. This is twice encoding-decoding but is not any issue.

We might see in future if should handle this check in util method itself or if you could check and file a pr fix that would be really appreciated. :)

You may refer:
- https://stackoverflow.com/questions/6224052/what-is-the-difference-between-a-string-and-a-byte-string
- https://stackoverflow.com/questions/606191/convert-bytes-to-a-string

**Comment by jitendra-1217** [comment]
@SurajB : Closing this issue now referring to https://github.com/razorpay/razorpay-python/issues/65#issuecomment-485752662, please do re-open/comment if issue persists.
