### ISSUE TITLE
Fetching Email address respective to all successful Payment ID!

### ISSUE THREAD

**Issue by Sachinjha469** [razorpay/razorpay-python#69]
I am trying to use a query something like this:
`if Successful:
      client.payment.all().values('email')`

In order to extract the email id's of all the payers who successfully completed the Payment Procedure! Is there some query to resolve my issue?

**Comment by harman28** [comment]
This is correct, you'll need to fetch all payments and log their emails. Rather than using an API for this, you may find it easier to download a report from your Razorpay merchant dashboard and consume that instead.
