### ISSUE TITLE
Descriptive error messages needed instead of "The requested URL was not found on the server" 

### ISSUE THREAD

**Issue by navidkhn1** [razorpay/razorpay-python#71]
If a product hasn't been activated through Razorpay's dashboard, such as Subscriptions, accessing related APIs through the cli returns "The requested URL was not found on the server". 

This should instead return a proper descriptive message showcasing the problem.

**Comment by harman28** [comment]
Agree with this, our API response should tell you that the product or feature is not enabled, and not simply say that the "URL is not found", which is misleading. There is a larger project in the works right now which will allow us to return smarter error codes. Closing this for now as it is unrelated to the python library, which is restricted to working with what the API returns.
