### ISSUE TITLE
AttributeError: module 'razorpay' has no attribute 'Client'

### ISSUE THREAD

**Issue by vinaykr579** [razorpay/razorpay-python#73]
I am getting error **AttributeError: module 'razorpay' has no attribute 'Client'** 
python setup : python 3.5 venv

import razorpay

razorpay.Client(auth=("****", "*****"))

**Comment by 7saikat7** [comment]
how did you solved it ?

**Comment by duraiganesh0** [comment]
Hey @vinaykr579 I am also facing the same issue. How did you solve it?

**Comment by thearyanag** [comment]
This issue arises if the name of the file is same as that of the module ! Your file name would be razorpay.py

**Comment by 7saikat7** [comment]
ya ya it solved a lot ago and working fine in TEST MODE ... sorry i forgot to mention here ,

razorpay==1.2.0 add this in requirements and install it, I don't have any razorpay.py file !

**Comment by princepatoliya** [comment]
Also, no folder should be named RazorPay.
