### ISSUE TITLE
Razorpay js Script not executing in Chrome.

### ISSUE THREAD

**Issue by Aniket-Singla** [razorpay/razorpay-python#74]
Google chrome displays the following error and says that razorpay failed to load.
```
Refused to display 'https://api.razorpay.com/v1/checkout/public' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```

I am new to such scripts. What I am able to dig from the error message is the link ```https://api.razorpay.com/v1/checkout/public``` has set the response header X-Frame Options to SameOrigin, which should mean that there is a problem on above link. 

Suggest me what to do with this error. This seems to be chrome specific error. But being one of the most widely used browser razorpay must look into it.

**Comment by harman28** [comment]
Closing this, unrelated to the python library. The issue looks genuine though, can you try raising this to our [support portal](https://razorpay.com/support)?
