### ISSUE TITLE
Manual Signature Matching 

### ISSUE THREAD

**Issue by chandrabhanchaudhary** [razorpay/razorpay-python#75]
Hii i'm trying to match signature of Razor Pay but i'm not able to match that 
please find below code which uses that 

 Func<RazorPayCheckoutResponse, bool> RazorPaySignatureMatching = s =>{
            try
            {
                ASCIIEncoding encoding = new ASCIIEncoding();
                HMACSHA256 hmacsha256 = new HMACSHA256(encoding.GetBytes(RAZOR_PAY_SECRET));
                string genSignature = string.Empty;
                hmacsha256.ComputeHash(encoding.GetBytes(s.razorpay_payment_id + "|" + s.razorpay_subscription_id)).ToList().ForEach(x=> genSignature += String.Format("{0:x2}", x));
                return String.Equals(s.razorpay_signature,genSignature);
            }
            catch
            {
                return false;
            }  
        };

**Comment by harman28** [comment]
Closing this, appears to be on the wrong repo.
