### ISSUE TITLE
Support for python 3.7

### ISSUE THREAD

**Issue by singhgautam7** [razorpay/razorpay-python#76]
I am currently using python 3.7.x and as seen in razorpay python documentation, it has support only till 3.6. Is there anything I can do to integrate razorpay with my project?

**Comment by vocuzi** [comment]
Can someone please respond to this issue ?

**Comment by vocuzi** [comment]
It supports python 3.7 and 3.8 as well.

**Comment by ankitdas13** [comment]
@singhgautam7 Apologise for the long delay. It supports Python v3.7 - v3.10 , could you please let us know if this issue has been resolved. If not, please let us know we will help you

**Comment by ankitdas13** [comment]
Closing this issue for now, due to not getting any response. If you are getting any issues with python v3.7 or v3.10. Please let us know we will help you
