### ISSUE TITLE
Recurring Payments APIs

### ISSUE THREAD

**Issue by Goutam192002** [razorpay/razorpay-python#77]
How do I create recurring payments using razorpay-pytho sdk?
Here is the rest API reference: https://razorpay.com/docs/recurring-payments/api/subsequent-payments-card/

**Comment by harman28** [comment]
@Goutam192002 We don't have support for recurring payments on the Python library yet. You can hit the API directly or extend the request class to add a function for this. If you do the latter, please be sure to raise a PR for us too! :)

**Comment by Goutam192002** [comment]
I'd love to raise a PR. 
I'd need some guidance though, on how to get started with contributing to the project.
 This is the first Open-Source contribution I'd be doing😅.

**Comment by Goutam192002** [comment]
looks like there already exists a pull request which is yet to be merged.
Here: https://github.com/razorpay/razorpay-python/pull/41

**Comment by ankitdas13** [comment]
Closing this issue because it has already been implemented in one of releases, you can check this [doc](https://github.com/razorpay/razorpay-python/blob/master/documents/emandate.md#create-a-recurring-payment) for reference
