### ISSUE TITLE
Missing function to fetch payment details made to a Virtual Account if payment is UPI Transfer

### ISSUE THREAD

**Issue by mascot6699** [razorpay/razorpay-python#80]
The docs says for UPI transaction there is a separate api call ([here](https://razorpay.com/docs/smart-collect/api/fetch/#upi)) to fetch payment details given an id. 

I see something similar is already done for `bank_account` payments. ([here](https://github.com/razorpay/razorpay-python/blob/5bc63fd8452165a4b54556888492e555222c8afe/razorpay/resources/payment.py#L94)) so please provide another function to fetch particular `upi_transfer` payment details.

Happy to give a PR sometime over the weekend if need be.

**Comment by harman28** [comment]
@mascot6699 You're right, there's no function for upi transfers, since support for that was added very recently. We'll try and package this in our next release, but we'd love it if you could raise a PR to do this as well!
