### ISSUE TITLE
Returning result in verify_signature not updated in PyPI

### ISSUE THREAD

**Issue by shahharsh176** [razorpay/razorpay-python#86]
I can see that https://github.com/razorpay/razorpay-python/pull/67 was merged. But when I install razorpay package using pip, it's not reflected there. So, I think Source code package in PyPI is not up to date. So, I request you to update the same.

**Comment by ankitdas13** [comment]
@shahharsh176 My apologies for the long delay and also for the difficulties you have encountered. Could you let us know if this issue was resolved ? The changes are already updated in Pip

**Comment by ankitdas13** [comment]
Closing this issue for now, due to not getting any response. If the issue still persists there, then reopen this issue. Please let us know if you need any help.
